// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy9lre9lbwlCxRgAYob_u_8VEHjMRK8zw',
    appId: '1:870476070400:web:111188c606238ed9d762e5',
    messagingSenderId: '870476070400',
    projectId: 'wecourier-f72f2',
    authDomain: 'wecourier-f72f2.firebaseapp.com',
    storageBucket: 'wecourier-f72f2.firebasestorage.app',
    measurementId: 'G-JESVYWXSSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVK5sgyt_RBeLmRdzJW-Dyr-g7jp_zjA',
    appId: '1:870476070400:android:55764e0d6ba8e67ad762e5',
    messagingSenderId: '870476070400',
    projectId: 'wecourier-f72f2',
    storageBucket: 'wecourier-f72f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfzlqFzPVl5-HqSR0uVUqXNVi0CYFckn8',
    appId: '1:870476070400:ios:eb232965e853c238d762e5',
    messagingSenderId: '870476070400',
    projectId: 'wecourier-f72f2',
    storageBucket: 'wecourier-f72f2.firebasestorage.app',
    iosBundleId: 'com.wecourier.merchant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfzlqFzPVl5-HqSR0uVUqXNVi0CYFckn8',
    appId: '1:870476070400:ios:eb232965e853c238d762e5',
    messagingSenderId: '870476070400',
    projectId: 'wecourier-f72f2',
    storageBucket: 'wecourier-f72f2.firebasestorage.app',
    iosBundleId: 'com.wecourier.merchant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy9lre9lbwlCxRgAYob_u_8VEHjMRK8zw',
    appId: '1:870476070400:web:7e08686498933eecd762e5',
    messagingSenderId: '870476070400',
    projectId: 'wecourier-f72f2',
    authDomain: 'wecourier-f72f2.firebaseapp.com',
    storageBucket: 'wecourier-f72f2.firebasestorage.app',
    measurementId: 'G-7GL12JRBEC',
  );
}
